### ISSUE TITLE
Way of passing media queries through?

### ISSUE THREAD

**Issue by PhilippeGauthier** [imgix/imgix-statamic#11]
Is there a way of passing the `sizes` attribute with media queries like I see on this guide? https://docs.imgix.com/tutorials/responsive-images-srcset-imgix

As far as I can tell just the DPR resolutions?

**Comment by paulstraw** [comment]
Hey @PhilippeGauthier, you should be able to just pass this in as expected, e.g.

```
{{ imgix:responsive_image_tag path="dogs.png" w="200" rot="10" alt="Some dogs!" sizes="(min-width: 36em) 33.3vw, 100vw" }}
```

Feel free to reopen this if you're still running into issues!

**Comment by PhilippeGauthier** [comment]
Ah thanks. Is there a way of passing breakpoints to generate varied width images similar to the code on your post?

```
<img
  srcset="https://assets.imgix.net/unsplash/bridge.jpg?w=1024&h=1024&fit=crop 1024w,
          https://assets.imgix.net/unsplash/bridge.jpg?w=640&h=640&fit=crop 640w,
          https://assets.imgix.net/unsplash/bridge.jpg?w=480&h=480&fit=crop 480w"
  src="https://assets.imgix.net/unsplash/bridge.jpg?w=640&h=640&fit=crop"
  sizes="(min-width: 36em) 33.3vw, 100vw"
>
```

**Comment by paulstraw** [comment]
imgix-statamic's `responsive_image_tag` uses density descriptors. You can set the `responsive_resolutions` to an array of numbers if you want more than the default 1x and 2x.

**Comment by PhilippeGauthier** [comment]
Ah it'd be cool if you were able to either pass multiple width's in the `responsive_image_tag` width parameter or have a `responsive_widths` config variable. Right now as far as I can tell the only way to generate multiple widths with the Imgix Statamic addon is with inline css styles that target element classes or IDs right?

**Comment by paulstraw** [comment]
Currently, imgix-statamic doesn't support output of fully-customized `picture` tags or `srcset`s. https://github.com/imgix/imgix.js might do what you're looking for.
