### ISSUE TITLE
Update for Statamic V3?

### ISSUE THREAD

**Issue by austriker27** [imgix/imgix-statamic#21]
Please provide the following information and someone from @imgix/imgix-sdk-team will respond to your issue shortly.

- [x] Please search through the [existing issues](https://github.com/imgix/imgix-statamic/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your feature has already been discussed.
- [x] Please take a moment to find out whether your idea fits with the scope and aims of this project.

Are there plans for this addon to be updated for Statamic V3? 

Thanks!

**Comment by sherwinski** [comment]
Hey @austriker27 👋 
We don't currently have a timeline for updating to v3, although I am curious how seamless the process would be using their [migrator package](https://github.com/statamic/migrator). I can look into it this week and get back to you.

Related to #17

**Comment by austriker27** [comment]
> Hey @austriker27 👋
> We don't currently have a timeline for updating to v3, although I am curious how seamless the process would be using their [migrator package](https://github.com/statamic/migrator). I can look into it this week and get back to you.
> 
> Related to #17

Hi @sherwinski did you have a chance to look at migration for V3? Thanks!

**Comment by sherwinski** [comment]
Hey @austriker27 
Apologies for the silence here, end-of-the-year priorities forced me to postpone this but I am finally getting around to looking into it.

**Comment by sherwinski** [comment]
Hey @austriker27 

Just wanted to swing back and give you an update. Unfortunately, the work needed to upgrade and sufficiently test this project for Statamic v3 is a lot more than what our team has capacity for at the moment. I've added an item to our backlog to revisit this in the future but for the time being I will be closing this issue.

In an attempt to not leave you so empty-handed here, you may also want to look into this third party [laravel package](https://github.com/Otisz/Laravel-Imgix) for imgix or think about extending the official [imgix-php](https://github.com/imgix/imgix-php/) package for your needs.

**Comment by austriker27** [comment]
Thanks for the heads up, I appreciate it!
