### ISSUE TITLE
feat: statamic v3 support

### ISSUE THREAD

**Issue by peterjaap** [imgix/imgix-statamic#23]
Any plans to provide Statamic v3 support?

**Comment by luqven** [comment]
Hey @peterjaap, thanks for opening this issue!

We don't currently have this on our roadmap, but if there's enough community interest, we'd be happy to consider it. 

If you need Statamic v3 support to get started with imgix, let us know in a comment or reach out to support@imgix.com. This helps us better prioritize this work.
