### ISSUE TITLE
Alternative text (alt) attributes

### ISSUE THREAD

**Issue by chris-79** [imgix/imgix-statamic#3]
This does not appear to allow for alternative text attributes in either **v1** or **v2** for the `imgix:image_tag`, `imgix:responsive_image_tag`, and `imgix:picture_tag` functions.

`alt`, `longdesc`, and/or `title` are required by [Section 508](http://webaim.org/techniques/alttext) of the [Rehabilitation Act of 1973](https://en.wikipedia.org/wiki/Rehabilitation_Act_of_1973).

It'd be nice to have the ability to use `data-`, `aria-label`, and `aria-labelledby` attributes, too :)

For the full text of Section 508, please see the [official government 508 web site](http://www.section508.gov/).

**Comment by paulstraw** [comment]
Great point! Would you like to submit a pull request for this? Either way, I'm more than happy to add support for these attributes. Let me know!

**Comment by chris-79** [comment]
I'd love to be able to, but I have no experience with the tools you're using to build it :-/

**Comment by paulstraw** [comment]
No problem, I'll get this added! 😁

**Comment by paulstraw** [comment]
Hey @chris-79, this should be all good to go now in the 1.2.0 and 2.2.0 releases. Currently, `alt`, `longdesc`, `title`, `data-*`, and `aria-*` will be passed through to generated `img` tags. Let me know if you have any questions!

**Comment by chris-79** [comment]
**_Rock on!_** 👍😎
