### ISSUE TITLE
Error with duplicate Imgix attributes

### ISSUE THREAD

**Issue by chris-79** [imgix/imgix-statamic#5]
**Error message:** "rawurlencode() expects parameter 1 to be string, array given"  
https://gist.github.com/chris-79/4b7596d72d9d644af6d92b0dc2649b18

**Template Code:**  

```
{{ imgix:image_tag path="/assets/img/homepage/cassiewrightphoto00075.jpg" w="200" rot="10" auto="format" rot="90" alt="" }}
```

As you can see in this bit of the error, the second `rot` attribute (`rot="90"`) is causing the plugin to convert `rot` into an array:

```
'imgix_attributes' => array('w' => '200', 'rot' => array('10', '90'), 'auto' => 'format')
```

Granted, this was **_my_** error adding a second, duplicate attribute… palm→face

Just thought I'd throw this out there.

¯\_(ツ)_/¯

**Comment by paulstraw** [comment]
Ah, yeah. Unfortunately, I don't know if there's anything I can do about this, as it's just how Statamic plugins interpret duplicate parameters. @jasonvarga, does that sound right?

**Comment by jasonvarga** [comment]
Not sure if I knew it did that or not. You may have discovered a feature! But yeah, kinda just the way it is. Don't duplicate your parameters :)

**Comment by paulstraw** [comment]
There we have it, straight from the man himself. 👌

Thanks Jason! Closing this.

**Comment by chris-79** [comment]
Good to know! Thanks, all 😀
