### ISSUE TITLE
Parsing of modifiers fails

### ISSUE THREAD

**Issue by chris-79** [imgix/imgix-statamic#6]
I'm trying to remove a directory from the path of my image, but the `remove_left` modifier fails.

```
{{ imgix:responsive_image_tag path="{ banner_image remove_left='/assets' }" auto="format" aria-labelledby="{ page-title }" w="1000" }}
```

Results in:

```
<img srcset="https://coeweb.imgix.net/{ banner_image remove_left='/assets' }?ixlib=php-1.1.0&w=1000& 1x,https://coeweb.imgix.net/{ banner_image remove_left='/assets' }?dpr=2&ixlib=php-1.1.0&w=1000& 2x" src="https://coeweb.imgix.net/{ banner_image remove_left='/assets' }?ixlib=php-1.1.0&w=1000&" >
```

**Comment by chris-79** [comment]
Also, the `or` operator doesn't work, as in...

```
{ banner_image or missing_image }
```

**Comment by jackmcdade** [comment]
Currently modifiers inside tag parameters are not supported.

**Comment by paulstraw** [comment]
Well there we go. Thanks so much @jackmcdade.

**Comment by jasonvarga** [comment]
@chris-79 You could slap together a `remove_assets` modifier that just does the equivalent of `remove_left="/assets"`. Then you'd be able to do `path="{ banner_image | remove_assets }"`

...or even a macro: `{ banner_image | macro:remove_assets }`

```
remove_assets:
  remove_left: "/assets"
```
