### ISSUE TITLE
FR: Text Overlays

### ISSUE THREAD

**Issue by chris-79** [imgix/imgix-statamic#7]
So, imgix has this __really__ cool feature where text can be put on top of an image like a watermark.

Is there maybe some way that new parameters can be added to take advantage of this? Maybe something like:

```
{{ imgix:image_tag
    path="{ banner_image }"
    fit="crop"
    auto="compress,format"
    w="350"
    h="200"
    alt="{ title }"
    overlay_txt="{ title }"
    overlay_fit="max"
    overlay_align="center,middle"
    overlay_lead="10"
    overlay_track="-5"
    }}
```

Where the `overlay_` keyword can be used in place of `mark` and `txt` for these attributes:
- [`~text`](https://docs.imgix.com/apis/url/typesetting-endpoint/~text)
- [`markfit`](https://docs.imgix.com/apis/url/watermark/markfit)
- [`markalign`](https://docs.imgix.com/apis/url/watermark/markalign)
- [`markx`](https://docs.imgix.com/apis/url/watermark/markx)
- [`marky`](https://docs.imgix.com/apis/url/watermark/marky)
- [`markw`](https://docs.imgix.com/apis/url/watermark/markw)
- [`markh`](https://docs.imgix.com/apis/url/watermark/markh)
- [`markpad`](https://docs.imgix.com/apis/url/watermark/markpad)
- [`markscale`](https://docs.imgix.com/apis/url/watermark/markscale)
- [`txtlead`](https://docs.imgix.com/apis/url/typesetting-endpoint/txtlead)
- [`txttrack`](https://docs.imgix.com/apis/url/typesetting-endpoint/txttrack)
- [`txtalign`](https://docs.imgix.com/apis/url/text/txtalign)
- [`txtclr`](https://docs.imgix.com/apis/url/text/txtclr)
- [`txtfit`](https://docs.imgix.com/apis/url/text/txtfit)
- [`txtfont`](https://docs.imgix.com/apis/url/text/txtfont)
- [`txtsize`](https://docs.imgix.com/apis/url/text/txtsize)
- [`txtshad`](https://docs.imgix.com/apis/url/text/txtshad)

Right now, the regular `txt="whatever"` works fine with short words/phrases:

![](https://i.imgur.com/gqgxFMv.jpg)

… but longer ones are not so nice:

![](https://i.imgur.com/h0z7XEh.jpg)

**Comment by paulstraw** [comment]
Hey @chris-79, I'm not totally sure I follow why we would use `overlay_*` instead of the existing parameter names. Could you clarify the goal of that change?

**Comment by chris-79** [comment]
Mostly just trying to get long text to wrap automatically.

Like this:

Saturday Seminars for 
Professional School 
Counselors

This gets squeezed into 1 line with the `txt=` parameter, like on the second example image.

The `~text` typesetting endpoint, however, _does_ seem to handle this correctly, so I thought maybe we could get that to hook-in with the watermark feature.

Would be nice if the regular `txt=` parameter supported automatically making text wrap to multiple lines, but it seems that's not a thing.

**Comment by paulstraw** [comment]
Sure. You should already be able to use the typesetting endpoint in this way with imgix-statamic. Something like this:

```
{{ imgix:image_tag
  path="{ banner_image }"
  fit="crop"
  auto="compress,format"
  w="350"
  h="200"
  alt="{ title }"
  mark="https://assets.imgix.net/~text?fm=png&txtsize=36&w=600&txtfont=Avenir+Next+Condensed,Bold&txt=The+quick+brown+fox+jumps+over+the+lazy+dog.+The+five+boxing+wizards+jump+quickly.&txtpad=30&bg=3D4C5F&txtclr=fff"
}}
```

Is that not behaving as expected?

**Comment by chris-79** [comment]
Yeah, I guess that does work. Just super ugly and unreadable.

I like to operate on the premise of, "If I got hit by a bus, could my replacement look at this and figure out what's going on?"

¯\_(ツ)_/¯
