### ISSUE TITLE
Need more Pass-through Attributes

### ISSUE THREAD

**Issue by chris-79** [imgix/imgix-statamic#8]
Looks like these aren't being passed-through:

`id`, `class`, and `rel`

Might be more standard-ish ones, but I just came across these.

– Chris :)

**Comment by paulstraw** [comment]
Hey @chris-79, I'm adding all `<img>` and "Global attribute" values from the [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) to the attribute whitelist. That will include `id` and `class`, but `rel` in particular is supposed to be used only with `<a>`, `<area>`, and `<link>`.

**Comment by chris-79** [comment]
Sweet! 😄

**Comment by paulstraw** [comment]
Alright @chris-79, this has been updated + released in 1.1.1 and 2.2.1, for Statamic 1.x and 2.x, respectively.

**Comment by chris-79** [comment]
You rock, man! 😃
